export const GET_SKINFLUENCERS_REQUEST = "GET_SKINFLUENCERS_REQUEST";
export const GET_SKINFLUENCERS_SUCCESS = "GET_SKINFLUENCERS_SUCCESS";
export const GET_SKINFLUENCERS_FAILURE = "GET_SKINFLUENCERS_FAILURE";
