export const GET_SKINFLUENCERS_REQUEST = "GET_SKINFLUENCERS_REQUEST";
export const GET_SKINFLUENCERS_SUCCESS = "GET_SKINFLUENCERS_SUCCESS";
export const GET_SKINFLUENCERS_FAILURE = "GET_SKINFLUENCERS_FAILURE";

export const CREATE_SKINFLUENCER_REQUEST = "CREATE_SKINFLUENCER_REQUEST";
export const CREATE_SKINFLUENCER_SUCCESS = "CREATE_SKINFLUENCER_SUCCESS";
export const CREATE_SKINFLUENCER_FAILURE = "CREATE_SKINFLUENCER_FAILURE";

export const DELETE_SKINFLUENCER_REQUEST = "DELETE_SKINFLUENCER_REQUEST";
export const DELETE_SKINFLUENCER_SUCCESS = "DELETE_SKINFLUENCER_SUCCESS";
export const DELETE_SKINFLUENCER_FAILURE = "DELETE_SKINFLUENCER_FAILURE";
