export const GET_RESELLERS_REQUEST = "GET_RESELLERS_REQUEST";
export const GET_RESELLERS_SUCCESS = "GET_RESELLERS_SUCCESS";
export const GET_RESELLERS_FAILURE = "GET_RESELLERS_FAILURE";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

export const UPDATE_COMMENTS = "UPDATE_COMMENTS";
