export const GET_RESELLERS_REQUEST = "GET_RESELLERS_REQUEST";
export const GET_RESELLERS_SUCCESS = "GET_RESELLERS_SUCCESS";
export const GET_RESELLERS_FAILURE = "GET_RESELLERS_FAILURE";

export const CREATE_RESELLER_REQUEST = "CREATE_RESELLER_REQUEST";
export const CREATE_RESELLER_SUCCESS = "CREATE_RESELLER_SUCCESS";
export const CREATE_RESELLER_FAILURE = "CREATE_RESELLER_FAILURE";

export const UPDATE_COMMENTS = "UPDATE_COMMENTS";
