export const GET_RESELLERS_REQUEST = "GET_RESELLERS_REQUEST";
export const GET_RESELLERS_SUCCESS = "GET_RESELLERS_SUCCESS";
export const GET_RESELLERS_FAILURE = "GET_RESELLERS_FAILURE";

export const CREATE_RESELLER_REQUEST = "CREATE_RESELLER_REQUEST";
export const CREATE_RESELLER_SUCCESS = "CREATE_RESELLER_SUCCESS";
export const CREATE_RESELLER_FAILURE = "CREATE_RESELLER_FAILURE";

export const DELETE_RESELLER_REQUEST = "DELETE_RESELLER_REQUEST";
export const DELETE_RESELLER_SUCCESS = "DELETE_RESELLER_SUCCESS";
export const DELETE_RESELLER_FAILURE = "DELETE_RESELLER_FAILURE";

export const GET_ONE_RESELLER_REQUEST = "GET_ONE_RESELLER_REQUEST";
export const GET_ONE_RESELLER_SUCCESS = "GET_ONE_RESELLER_SUCCESS";
export const GET_ONE_RESELLER_FAILURE = "GET_ONE_RESELLER_FAILURE";
