export const GET_THREADS_REQUEST = "GET_THREADS_REQUEST";
export const GET_THREADS_SUCCESS = "GET_THREADS_SUCCESS";
export const GET_THREADS_FAILURE = "GET_THREADS_FAILURE";

export const GET_ONE_THREAD_REQUEST = "GET_ONE_THREAD_REQUEST";
export const GET_ONE_THREAD_SUCCESS = "GET_ONE_THREAD_SUCCESS";
export const GET_ONE_THREAD_FAILURE = "GET_ONE_THREAD_FAILURE";

export const CREATE_THREAD_REQUEST = "CREATE_THREAD_REQUEST";
export const CREATE_THREAD_SUCCESS = "CREATE_THREAD_SUCCESS";
export const CREATE_THREAD_FAILURE = "CREATE_THREAD_FAILURE";
